<?php

$produtos = array(
    0 => array('nome'=>'Alex', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'alex.jpg'),
    1 => array('nome'=>'Benitez', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'benitez.jpg'),
    2 => array('nome'=>'Bolívar', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'bolivar.jpg'),
    3 => array('nome'=>'Carlitos', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'carlitos.jpg'),
    4 => array('nome'=>'Carpegiani', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'carpegiani.jpg'),
    5 => array('nome'=>'Chico Spina', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'chico-spina.jpg'),
    6 => array('nome'=>'Claudiomiro', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'claudiomiro.jpg'),
    7 => array('nome'=>'Clemer', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'clemer.jpg'),
    8 => array('nome'=>'Dalessandro', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'dalessandro.jpg'),
    9 => array('nome'=>'Leandro Damião', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'damiao.jpg'),
    10 => array('nome'=>'Elias Figueroa', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'elias-figueroa.jpg'),
    11 => array('nome'=>'Escurinho', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'escurinho.jpg'),
    12 => array('nome'=>'Fabiano Eller', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'fabiano-eller.jpg'),
    13 => array('nome'=>'Paulo Roberto Falcão', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'falcao.jpg'),
    14 => array('nome'=>'Fernandão', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'fernandao.jpg'),
    15 => array('nome'=>'Adriano Gabiru', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'gabiru.jpg'),
    16 => array('nome'=>'Pedro Iarley', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'iarley.jpg'), 
    17 => array('nome'=>'Índio', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'indio.jpg'),
    18 => array('nome'=>'Larry', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'larry.jpg'),
    19 => array('nome'=>'Lula', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'lula.jpg'),  
    20 => array('nome'=>'Manga', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'manga.jpg'),
    21 => array('nome'=>'Mauro Galvão', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'mauro-galvao.jpg'),
    22 => array('nome'=>'Nilmar', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'nilmar.jpg'),
    23 => array('nome'=>'Príncipe Jajá', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'principe-jaja.jpg'),
    24 => array('nome'=>'Rafael Sóbis', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'rafael-sobis.jpg'),
    25 => array('nome'=>'Rúben Paz', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'ruben-paz.jpg'),    
    26 => array('nome'=>'Cláudio Taffarel', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'taffarel.jpg'),
    27 => array('nome'=>'Tesourinha', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'tesourinha.jpg'),
    28 => array('nome'=>'Tinga', 'preco'=>'2500.00', 'nome completo'=>'', 'descricao'=>'', 'imagem'=>'tinga.jpg'), 
    29 => array('nome'=>'Valdomiro', 'preco'=>'2500.00','descricao'=>'', 'imagem'=>'valdomiro.jpg'),   
);
?>